Adds an example using the js library on the keyValue contract
dedis/cothority_template pull request #58
Opened 2019-10-22 12:25 UTC by nkcr

This PR adds explanations and an example of using our js/cothority library in the browser. It allows one to play with the keyValue contract.

Here is how it looks like:

<img width="1382" alt="Screenshot 2019-10-22 at 14 22 14" src="https://user-images.githubusercontent.com/1918021/67285299-9830ed00-f4d7-11e9-8794-984d4186fbd8.png">

2019-10-23 06:28 UTC, nkcr commented
@Charrlyine I mention you so you can follow the status of this PR and get notified when the js/example is merged into master.

2019-10-25 14:48 UTC, Gilthoniel commented
If you really want to use a different font, you can use Google Fonts that provide embedded solutions like:
```
<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i&display=swap" rel="stylesheet"> 
```

2019-10-25 14:59 UTC, nkcr commented
> you can use Google Fonts that provide embedded solutions

Sure, I embedded the font in order to have a kind of self-contained app that can be run locally (since it's the most probable use case of it) without relying on the external world. But maybe that doesn't make sense. 
Are you concerned about the extra space the fonts take?

2019-10-25 15:02 UTC, Gilthoniel commented
Yeah kind of. It adds something to the template that is not really useful. I guess a template should be as small as possible.

2019-10-28 10:00 UTC, nkcr commented
All right, static fonts import removed.

2019-10-28 10:47 UTC, Gilthoniel requested changes

2019-10-28 10:47 UTC, Gilthoniel commented on external/js/assets/fonts/Roboto/LICENSE.txt
> +
You forgot those ones ?

2019-10-28 10:48 UTC, nkcr commented on external/js/assets/fonts/Roboto/LICENSE.txt
> +
😱

2019-10-28 11:40 UTC, Gilthoniel approved these changes

2019-10-28 11:40 UTC, merged